# Copyright 2017-2022 Akretion France (http://www.akretion.com/)
# @author: Alexis de Lattre <alexis.delattre@akretion.com>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from lxml import etree

from odoo import api, models


class AccountMove(models.Model):
    _inherit = "account.move"

    @api.model
    def _cii_get_party_identification(self, commercial_partner):
        res = super()._cii_get_party_identification(commercial_partner)
        # partner.siret has a value even if partner.nic == False
        if commercial_partner.siren and commercial_partner.nic:
            res["0002"] = commercial_partner.siret
        return res

    def _cii_add_trade_agreement_block(self, trade_transaction, ns):
        super()._cii_add_trade_agreement_block(trade_transaction, ns)
        company = self.company_id
        # When the company has no VAT number (e.g. French "franchise en base de TVA" /
        # micro-entrepreneur under article 293 B CGI), the Factur-X schematron rule BR-E-02
        # requires that invoices containing VAT-exempt lines (category "E") include at least
        # one of: Seller VAT Identifier (BT-31), Seller tax registration identifier (BT-32),
        # or Seller tax representative VAT identifier (BT-63).
        # Without a VAT number, BT-31 is not generated by the base module. We therefore add
        # the company SIRET as BT-32 (SpecifiedTaxRegistration/ID with schemeID "FC").
        if not company.vat and company.partner_id.siren:
            trade_agreement = trade_transaction.find(
                ns["ram"] + "ApplicableHeaderTradeAgreement"
            )
            if trade_agreement is not None:
                seller = trade_agreement.find(ns["ram"] + "SellerTradeParty")
                if seller is not None:
                    seller_tax_reg = etree.SubElement(
                        seller, ns["ram"] + "SpecifiedTaxRegistration"
                    )
                    seller_tax_reg_id = etree.SubElement(
                        seller_tax_reg, ns["ram"] + "ID", schemeID="FC"
                    )
                    seller_tax_reg_id.text = company.partner_id.siret
