# -*- coding: utf-8 -*-
# © 2016 Akretion (Alexis de Lattre <alexis.delattre@akretion.com>)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'L10n FR UBL',
    'version': '8.0.1.0.0',
    'category': 'French Localization',
    'license': 'AGPL-3',
    'summary': 'Adds SIRET in UBL XML files generated by Odoo',
    'author': 'Akretion,Odoo Community Association (OCA)',
    'website': 'http://www.akretion.com',
    'depends': ['l10n_fr_siret', 'base_ubl'],
    'installable': True,
    'auto_install': True,
}
