[project]
name = "odoo-addons-oca-l10n-france"
version = "19.0.20260720.0"
dependencies = [
    "odoo-addon-account_payment_fr_lcr==19.0.*",
    "odoo-addon-account_statement_import_fr_cfonb==19.0.*",
    "odoo-addon-l10n_fr_account_payment_intl_credit_transfer==19.0.*",
    "odoo-addon-l10n_fr_department==19.0.*",
    "odoo-addon-l10n_fr_department_oversea==19.0.*",
    "odoo-addon-l10n_fr_intrastat_service==19.0.*",
    "odoo-addon-l10n_fr_pos_caisse_ap_ip==19.0.*",
    "odoo-addon-l10n_fr_siret==19.0.*",
    "odoo-addon-l10n_fr_state==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
